//
// Created by Oleksandr Padko on 8/20/17.
//

#ifndef TICTACTOERECOGNITION_CELLCLASSIFIER_H
#define TICTACTOERECOGNITION_CELLCLASSIFIER_H


class CellClassifier {

};


#endif //TICTACTOERECOGNITION_CELLCLASSIFIER_H
